name: Deploy Laravel to HostAfrica

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, ctype, json, tokenizer, xml, curl, dom, fileinfo

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_PATH }}
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/vendor/*
            **/.env
            **/storage/logs/*
            **/storage/framework/cache/*
            **/storage/framework/views/*
            **/storage/framework/sessions/*

      - name: SSH into Server and Run Laravel Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          script: |
            cd ${{ secrets.FTP_PATH }}
            php artisan optimize:clear
            php artisan migrate --force
            php artisan storage:link
            chmod -R 775 storage bootstrap/cache
